# -*- coding: utf-8 -*-
"""PS13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ceu5hSnD1AT6wqlvyJMB-XH5SrYm4NSQ
"""

# Borhan Vishlaghi
# 04/17/2026
# Session 13 - Dynamic Arrays

# -----------------------------
# Problem 1
# -----------------------------

numbers = []

count = int(input("Enter number of items: "))

for i in range(count):
    while True:
        user_input = input("Enter a number: ")

        if user_input.isdigit():
            num = int(user_input)
            break
        else:
            print("Invalid input. Please enter a number.")

    numbers.append(num)

print("List:", numbers)


# -----------------------------
# Problem 2
# -----------------------------

numbers.insert(1, 99)
print("After insert 99:", numbers)


# -----------------------------
# Problem 3
# -----------------------------

index_99 = numbers.index(99)
numbers[index_99] = 100
print("After replace 99 with 100:", numbers)


# -----------------------------
# Problem 4
# -----------------------------

numbers2 = [500, 600, 700, 800, 900]
print("Second list:", numbers2)

numbers.extend(numbers2)
print("After extend:", numbers)


# -----------------------------
# Problem 5
# -----------------------------

numbers.remove(800)
print("After removing 800:", numbers)


# -----------------------------
# Problem 6
# -----------------------------

del numbers[2]
print("After deleting third item:", numbers)


# -----------------------------
# Problem 7
# -----------------------------

grades = ["A", "B", "C", "A", "A", "C"]


# -----------------------------
# Problem 8
# -----------------------------

count_A = grades.count("A")
print("Number of A grades:", count_A)


# -----------------------------
# Problem 9
# -----------------------------

index_B = grades.index("B")
print("Index of first B:", index_B)


# -----------------------------
# Problem 10
# -----------------------------

if "F" in grades:
    print("F is in the list")
else:
    print("F is not in the list")


# -----------------------------
# Problem 11
# -----------------------------

numbers2.clear()
print("After clearing second list:", numbers2)


# -----------------------------
# Problem 12
# -----------------------------

del numbers2

# This will cause error (as expected)
# print(numbers2)


# -----------------------------
# Problem 13
# -----------------------------

players = ["Rizzo", "Davis", "Baez", "Happ", "Bryan"]


# -----------------------------
# Problem 14
# -----------------------------

players.sort()
print("Sorted players:", players)


# -----------------------------
# Problem 15
# -----------------------------

players2 = players.copy()
print("players2:", players2)


# -----------------------------
# Problem 16
# -----------------------------

players2.reverse()

print("players:", players)
print("players2 reversed:", players2)